name = "bonpapi-final"
compatibility_date = "2024-10-10"

# For Cloudflare Pages output
pages_build_output_dir = "./dist"

# Astro Cloudflare adapter runtime
workers_dev = false

[vars]
NODE_VERSION = "18"
